version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    volumes:
      - ./db_files:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_aefjawef32234234
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
    command: bash -c "python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      gunicorn eccomerce_api.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
      - ./staticfiles:/usr/src/app/staticfiles
      - ./mediafiles:/usr/src/app/mediafiles
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_aefjawef32234234
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 8000

  nginx:
    build:
      context: ./nginx/
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./staticfiles:/home/app/staticfiles
      - ./mediafiles:/home/app/mediafiles
    depends_on:
      - backend